after_success: bash <(curl -s https://codecov.io/bash)

before_install: travis_retry composer self-update

branches:
    only: master

cache:
    directories: $HOME/.composer/cache

install: travis_retry composer install --dev --no-interaction --prefer-dist

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

script: vendor/bin/phpunit
