after_success: bash <(curl -s https://codecov.io/bash)

before_install: travis_retry composer self-update

branches:
    only: master

cache:
    directories: $HOME/.composer/cache

dist: trusty

install: travis_retry composer install --no-interaction --prefer-dist

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

script: vendor/bin/phpunit
